### ISSUE TITLE
【为缺少source标签的档案添加Ehentai元数据】这个插件可以增加延时的设定吗

### ISSUE THREAD

**Issue by Putarku** [chu-shen/LANraragi-scripts#1]
众所周知e站有反爬虫机制，高频爬取很容易就报错了，我自己测试是10秒左右搜一个就不怎么会触发封禁

**Comment by chu-shen** [comment]
已添加，插件下载：[addEhentaiMetadata.pm](https://github.com/chu-shen/LANraragi/blob/feat-ratingAndcomment/lib/LANraragi/Plugin/Scripts/addEhentaiMetadata.pm)

设置里直接填写秒数即可，比如 10 秒则直接填写 10

**Comment by chu-shen** [comment]
@Putarku 问题解决了吗👀

**Comment by Putarku** [comment]
> @Putarku 问题解决了吗👀

ok了没问题了
