### ISSUE TITLE
最新版本的lanraragi使用tag刮削插件时，hash错误

### ISSUE THREAD

**Issue by LemonSoda-RPG** [chu-shen/LANraragi-scripts#2]
<img width="706" alt="屏幕截图 2024-08-12 231358" src="https://github.com/user-attachments/assets/af1d8475-9bce-48b0-a37e-f69f9b763120">
 Can't use an undefined value as a HASH reference at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/EHentai.pm line 259.

**Comment by chu-shen** [comment]
前两天也遇到了，节点估计被 ban 了，换一个试试

**Comment by LemonSoda-RPG** [comment]
> 前两天也遇到了，节点估计被 ban 了，换一个试试

牛蛙  解决了  之前也被ban过，但是第一次见到这样的报错，谢谢大佬
